### ISSUE TITLE
Assalamu alaikum, Muhammadakbar

### ISSUE THREAD

**Issue by khaitbek** [MuhammadAkbar-Ramazonov/AnsorMed#1]
![image](https://user-images.githubusercontent.com/69072537/174722115-48e16f43-732d-4b2b-83f8-8dde5cae5e6c.png)
Mana shu qismida ikkalasi bir xil bo'lib qolibti. Shuni to'g'irlasak, yaxshi bo'lar edi :-)

**Comment by MuhammadAkbar-Ramazonov** [comment]
menda birinchi rasim ochmagani uchun ustozni ozlari pasdigi li cope qiling degandilar
