### ISSUE TITLE
Class 

### ISSUE THREAD

**Issue by khaitbek** [MuhammadAkbar-Ramazonov/AnsorMed#2]
![image](https://user-images.githubusercontent.com/69072537/174722686-3d8a1caa-b28b-4271-a795-1ec1cb603c26.png)

Sectionlarga nom berishda ma'noli nomdan foydalansan yaxshi bo'lar edi. Masalan, eng birinchi sectionga intro yoki hero deb class berilsa va qolgan sectionlarga ichidagi contentga qarab class berilsa yaxshi bo'lar edi :-)

**Comment by MuhammadAkbar-Ramazonov** [comment]
xop raxmat to'g'rladm xamma section classlarni
