### ISSUE TITLE
Box-model

### ISSUE THREAD

**Issue by khaitbek** [MuhammadAkbar-Ramazonov/AnsorMed#3]
![image](https://user-images.githubusercontent.com/69072537/174723345-a7464912-bcb9-45e3-b1b0-94620abc9103.png)
Bu yerda <a> elementini o'rab turgan <div> ga padding-bottom bergansiz. Lekin padding-bottomni umumiy katta <section> ga bersak, menimcha yaxshi bo'lar edi

**Comment by MuhammadAkbar-Ramazonov** [comment]
xop raxmat buni ham tog'irladm :)
