### ISSUE TITLE
Semantika

### ISSUE THREAD

**Issue by khaitbek** [MuhammadAkbar-Ramazonov/AnsorMed#4]
![image](https://user-images.githubusercontent.com/69072537/174724313-16d215d4-337b-4dbb-a3a2-80339a740bf6.png)
Bu yerda esa footerni ichida nav kelgan. Footerni ichida nav ishlatilinmaydi va o'rniga ul li a elementlari ishlatilinsa yaxshi bo'lar edi :-)

**Comment by MuhammadAkbar-Ramazonov** [comment]
xop raxmat to'g'irladm
