### ISSUE TITLE
css order

### ISSUE THREAD

**Issue by khaitbek** [MuhammadAkbar-Ramazonov/AnsorMed#5]
![image](https://user-images.githubusercontent.com/69072537/174724810-a70c6b44-4620-432e-83b1-fd7aa0f3bb6d.png)
Bu yerda paddingni teparoqda bersak yaxshi bo'lar edi :-)

**Comment by MuhammadAkbar-Ramazonov** [comment]
xo'p raxmat to'g'irladm
